name: Run Postman Tests

on:
  push:
    branches:
      - master  # Change to your target branch

jobs:
  postman-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Postman Collection
        continue-on-error: true
        shell: cmd
        run: |
          newman run Energy360Apis.postman_collection.json -e 360.postman_environment.json --insecure --folder "Authorization" -r html --reporter-html-export newman-report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: newman-report.html
