name: Run Postman Tests

on:
  push:
    branches:
      - master  # Change to your target branch
#test2
jobs:
  postman-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Postman Collection
        continue-on-error: true
        shell: cmd
        run: |
          newman run Energy360Apis.postman_collection.json ^
            -e 360.postman_environment.json ^
            --folder "Authorization" ^
            --insecure ^
            --timeout-request 10000 ^ 
             -r html ^
            --reporter-html-export newman-report.html

      - name: Send Email with Report
        continue-on-error: true
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Postman Test Report
          to: ${{ secrets.EMAILTO }}
          from: ${{ secrets.EMAIL }}
          body: |
            Hello,

            The latest Postman test run has completed. Please find the attached HTML report.

            Regards,
            Youssef Soltan
          attachments: newman-report.html
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: C:/Users/ysoltan/IdeaProjects/Letcode/newman-report.html
          overwrite: 'true'
